apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: hello
spec:
  topic: hellotopic
  routes: 
    default: /SubscribeHello
  pubsubname: pubsub
scopes:
  # - helloworldpublish # Jeg sender kun på hellotopic, så jeg behøver ikke lytte :-)
  - helloworldsubscribe
